In [68]:
import openai
import instructor
import tiktoken
import pandas as pd
import numpy as np

from pydantic import BaseModel, Field
from qdrant_client import QdrantClient
from qdrant_client.models import (
    Filter,
    FieldCondition,
    FusionQuery,
    MatchValue,
    MatchAny,
    VectorParams,
    Distance,
    SparseVectorParams,
    Modifier,
    PayloadSchemaType,
    Document,
    PointStruct,
    Prefetch,
    FusionQuery,
    RrfQuery,
    Rrf
)

### Qdrant collection for Hybrid Search

In [34]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [35]:
qdrant_client.create_collection(
    collection_name="Amazon-reviews-collection-01",
    vectors_config={
        "text-embedding-3-small": VectorParams(size=1536, distance=Distance.COSINE)
    }
)

True

In [36]:
qdrant_client.create_payload_index(
    collection_name="Amazon-reviews-collection-01",
    field_name="parent_asin",
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

### Embedding Functions

In [42]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input=text,
        model=model
    )
    return response.data[0].embedding

In [43]:
def get_embedding_batch(text_list, model="text-embedding-3-small", batch_size=100):
    
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Processed {counter * batch_size} of {len(text_list)}")
        counter += 1
    
    return all_embeddings

### Retreive all item IDs from Amazon Items Qdrant Collection

### Read the sampled dataset with Amazon inventory data

In [19]:
data_reviews = pd.read_json("../../data/Books_2022_2023_with_category_ratings_10_sample_1000.jsonl", lines=True)

In [20]:
data_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5,"Fits it's description as a ""biopedia.""",As a lifelong fan of Leon Russell and his musi...,[],1662431155,1662431155,AGKWDJVUMB2EI7U7QHNQWCDH6BDQ,2021-08-05 17:59:11.789,5,True
1,5,Good Devotional for Couples Looking to Connect...,My wife and I have been looking for ways to co...,[],1638787158,1638787158,AFLX66DKF6R3H6OEOC3TIVAYXZIQ,2022-08-24 10:08:38.564,0,False
2,5,A real Sophie’s Choice dilemma,This psychological suspense had a Sophie’s Cho...,[],1728250366,1728250366,AFAYQWKMEVX7GKQ7GZNQXJ7ORLWA,2022-05-04 01:00:59.079,0,False
3,5,A Much Needed Cookbook for Fall and Winter,So many good recipes in this book. The book is...,[],1621458288,1621458288,AE46NJ5H3EJIEHPS3CMZSHQISACA,2022-12-13 00:21:08.059,0,True
4,1,Fake,How is possible that a person can imitate Anth...,[],B0BMJQ2K4B,B0BMJQ2K4B,AH4UCXO5DN4ISACGJEEBGHB35U7Q,2022-12-20 13:25:25.645,9,False

### Functions for pre-processing reviews

In [27]:
def process_reviews(row):
    return f"{row['title']} {row['text']}"

In [28]:
def token_count(row, model="text-embedding-3-small"):
    
    encoding = tiktoken.encoding_for_model(model)
    
    return len(encoding.encode(row["preprocessed_data"]))

In [29]:
data_reviews['preprocessed_data'] = data_reviews.apply(process_reviews, axis=1)
data_reviews['token_count'] = data_reviews.apply(token_count, axis=1)

In [30]:
data_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,preprocessed_data,token_count
0,5,"Fits it's description as a ""biopedia.""",As a lifelong fan of Leon Russell and his musi...,[],1662431155,1662431155,AGKWDJVUMB2EI7U7QHNQWCDH6BDQ,2021-08-05 17:59:11.789,5,True,"Fits it's description as a ""biopedia."" As a li...",48
1,5,Good Devotional for Couples Looking to Connect...,My wife and I have been looking for ways to co...,[],1638787158,1638787158,AFLX66DKF6R3H6OEOC3TIVAYXZIQ,2022-08-24 10:08:38.564,0,False,Good Devotional for Couples Looking to Connect...,364
2,5,A real Sophie’s Choice dilemma,This psychological suspense had a Sophie’s Cho...,[],1728250366,1728250366,AFAYQWKMEVX7GKQ7GZNQXJ7ORLWA,2022-05-04 01:00:59.079,0,False,A real Sophie’s Choice dilemma This psychologi...,46
3,5,A Much Needed Cookbook for Fall and Winter,So many good recipes in this book. The book is...,[],1621458288,1621458288,AE46NJ5H3EJIEHPS3CMZSHQISACA,2022-12-13 00:21:08.059,0,True,A Much Needed Cookbook for Fall and Winter So ...,32
4,1,Fake,How is possible that a person can imitate Anth...,[],B0BMJQ2K4B,B0BMJQ2K4B,AH4UCXO5DN4ISACGJEEBGHB35U7Q,2022-12-20 13:25:25.645,9,False,Fake How is possible that a person can imitate...,50

In [31]:
len(data_reviews)

6390

In [32]:
data_reviews = data_reviews[data_reviews["token_count"] < 8192]
len(data_reviews)

6390

In [33]:
data_reviews["token_count"].sum()

np.int64(733284)

### Preprocess Reviews data

In [38]:
data_to_embed_review = data_reviews[["preprocessed_data", "parent_asin"]].to_dict(orient="records")

In [39]:
len(data_to_embed_review)

6390

### Embed Data

#### Amazon review data

In [40]:
text_to_embed_reviews = [item["preprocessed_data"] for item in data_to_embed_review]

In [44]:
dense_embeddings = get_embedding_batch(text_to_embed_reviews, batch_size=500)

Processed 500 of 6390
Processed 1000 of 6390
Processed 1500 of 6390
Processed 2000 of 6390
Processed 2500 of 6390
Processed 3000 of 6390
Processed 3500 of 6390
Processed 4000 of 6390
Processed 4500 of 6390
Processed 5000 of 6390
Processed 5500 of 6390
Processed 6000 of 6390
Processed 6500 of 6390

In [48]:
pointstructs = []
idx = 1
for embedding, data in zip(dense_embeddings, data_to_embed_review):
    pointstructs.append(
        PointStruct(
            id=idx,
            vector={
                "text-embedding-3-small": embedding
            },
            payload=data
        )
    )
    idx += 1

In [50]:
batch_size_qdrant = 100
counter = 1
total_points_to_upsert = len(pointstructs)
for i in range(0, total_points_to_upsert, batch_size_qdrant):
    batch = pointstructs[i:i+batch_size_qdrant]
    qdrant_client.upsert(
        collection_name="Amazon-reviews-collection-01",
        points=batch,
        wait=True
    )
    print(f"Processed {counter * batch_size_qdrant} of {total_points_to_upsert}")
    counter += 1

Processed 100 of 6390
Processed 200 of 6390
Processed 300 of 6390
Processed 400 of 6390
Processed 500 of 6390
Processed 600 of 6390
Processed 700 of 6390
Processed 800 of 6390
Processed 900 of 6390
Processed 1000 of 6390
Processed 1100 of 6390
Processed 1200 of 6390
Processed 1300 of 6390
Processed 1400 of 6390
Processed 1500 of 6390
Processed 1600 of 6390
Processed 1700 of 6390
Processed 1800 of 6390
Processed 1900 of 6390
Processed 2000 of 6390
Processed 2100 of 6390
Processed 2200 of 6390
Processed 2300 of 6390
Processed 2400 of 6390
Processed 2500 of 6390
Processed 2600 of 6390
Processed 2700 of 6390
Processed 2800 of 6390
Processed 2900 of 6390
Processed 3000 of 6390
Processed 3100 of 6390
Processed 3200 of 6390
Processed 3300 of 6390
Processed 3400 of 6390
Processed 3500 of 6390
Processed 3600 of 6390
Processed 3700 of 6390
Processed 3800 of 6390
Processed 3900 of 6390
Processed 4000 of 6390
Processed 4100 of 6390
Processed 4200 of 6390
Processed 4300 of 6390
Processed 4400 of 6390
Processed 4500 of 6390
Processed 4600 of 6390
Processed 4700 of 6390
Processed 4800 of 6390
Processed 4900 of 6390
Processed 5000 of 6390
Processed 5100 of 6390
Processed 5200 of 6390
Processed 5300 of 6390
Processed 5400 of 6390
Processed 5500 of 6390
Processed 5600 of 6390
Processed 5700 of 6390
Processed 5800 of 6390
Processed 5900 of 6390
Processed 6000 of 6390
Processed 6100 of 6390
Processed 6200 of 6390
Processed 6300 of 6390
Processed 6400 of 6390

### Hybrid Retrieval

Retrieve reviews only for the items we are interested in

In [59]:
def retrieve_prefiltered_review_data(query, parent_asins, qdrant_client, k=5):
   
    query_embedding = get_embedding(query)
    results = qdrant_client.query_points(
        collection_name="Amazon-reviews-collection-01",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion='rrf'),
        limit=k
    )

    return results

In [60]:
result = retrieve_prefiltered_review_data(
    "bad quality",
    ["1622775996", "B0C128NPC9", "0593547764", "B0C2S1JJWR"],
    qdrant_client,
    k=20
    )

In [61]:
result.points

[ScoredPoint(id=5715, version=61, score=0.5, payload={'preprocessed_data': "Did not dissapoint I love Greek retellings and this one did not disappoint.  I liked seeing the story of Medusa being told from a different perspective than what we usually get.  I think the author did a great job differentiating each sister's voice, and even if the titles hadn't been the sister's names, you would've been able to distinguish who was narrating.  I did enjoy the overall growth & development of the characters.<br /><br />I did find one of the sisters to be unbearable, and I just disliked her character so much, that it made it hard to read through her chapters, and although I love an advanced vocabulary, I felt distracted by the some of the vocabulary used at times.  Even with not liking the one sister, it was still an entertaining book, and I enjoyed it a whole lot.", 'parent_asin': '0593547764'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4928, version=53, score=0.33333334, payload={'preprocessed_data': 'The life of a true American classical music pioneer, chronicled in detail. I was Margaret Hillis’ young assistant conductor with the Elgin Symphony for three years in the 1980s, before her schedule got so busy she left her position as music director of the fine professional orchestra she had built in Chicago’s northwest suburbs.<br /><br />As an assignment my very first year I had the privilege (and, I anticipated, the terror) of preparing a local chorus for Miss Hillis to conduct the Beethoven Ninth Symphony with the ESO. Girding myself to be scared and intimidated in my meetings with her beforehand, I found Miss Hillis very much the opposite: invariably gracious, witty, helpful and no-nonsense—she ultimately was pleased with my work.<br /><br />Margaret Hillis and I became friends, (as one was able, considering the difference in our ages), so much so that she accepted my invitation to guest conduct my orchestra in Adrian, Michigan years later, and I visited privately in her dressing room after a rehearsal with the Elgin Symphony when she returned as a guest in 1994. I am told that that evening was the very last time she ever conducted anywhere. More importantly, she recommended me to be the founding conductor of the Chicago Bar Association Symphony, a post I still hold thirty-five years later, an act for which I will always be grateful.<br /><br />Hillis was marvelous at training a chorus. In my experience only her would-be mentor, Robert Shaw, could match her technical ability to get results from choral ensembles, preparing her Chicago Symphony Chorus to be remarkably flexible with CSO music directors as different as Reiner, Martinon, Solti or Barenboim.<br /><br />In performance, especially in front of an orchestra, she was less successful. One evening in fall 1984 I sat out in Hemmens Auditorium in Elgin listening to her lead the ESO in Ravel’s Daphnis & Chloe Suite No. 2. Despite the right notes in the right places, I remember thinking she was only getting about 60% of what I knew from experience the musicians in front of her could give in terms of intensity and emotional commitment. Mine was not a unique general assessment—it was a criticism that dogged Hillis her whole career, as Cheryl Frazes Hill points out numerous times in this exhaustive biography.<br /><br />A lapsed instrumentalist herself, winner of (eventually) nine Grammy Awards, I hardly think Margaret Hillis was intimidated by orchestras. Rather, it may have been exactly her skill at preparing a chorus—her ability to be so self-effacing in front of the music: to teach the notes, rhythms, harmonies, intonation, diction and pronunciation to such a high level of technical proficiency, all without imposing her own personality or injecting her own emotional intensity into the music—which allowed her to remain the favorite of CSO music directors through so many different tenures, temperaments and politics. How much of that self-effacement was innate and how much she forced upon herself to maintain an important position in what was then very much an all-male club Frazes Hill does at times consider; one is left to wonder if Hillis’ greatest skill as a conductor was ultimately her biggest weakness as a performing artist.<br /><br />Nothing I write takes away from what she achieved—indeed, an outdoor stage here at the offices of The American Prize National Nonprofit Competitions in the Performing Arts is named in her memory—nor does it take away from the deep affection I hold for her even now.<br /><br />Margaret Hillis was not the first important female conductor—Antonia Brico and Nadia Boulanger were a generation ahead—but surely she was the first to lead many concerts over many decades with an artistic organization of international stature. She was a true pioneer, a gracious human being and a worthy advocate for music.<br /><br />“Unsung Pioneer” is extremely well researched, highly detailed, balanced, sometimes repetitious and occasionally hyperbolic. Frazes Hill is best at putting in context the career Hillis forged, offering a clear perspective of the times in which she lived…especially as it related to women in professional music in the United States in the decades immediately following the Second World War.<br /><br />It is good to have her story available now, and for all time, through this fine volume. Thanks to Frazes Hill, Margaret Hillis is unsung no longer.', 'parent_asin': '1622775996'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=5938, version=63, score=0.25, payload={'preprocessed_data': 'Must read for women! This inspirational book is an absolute must read. I love how Katrina’s vulnerability and raw emotions unfold page after page. It is easy to read in short sessions and gives you a lot to contemplate after. Strong women everywhere will love this compilation.', 'parent_asin': 'B0C128NPC9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1574, version=19, score=0.2, payload={'preprocessed_data': 'A Classic This is not just Margaret Hillis’s story—it is our story—conductors, women, musicians of all stripes . . . humans.<br /><br />Unsung Pioneer reads like a novel, captivating in its human drama.  Yes, it is an historical presentation of the life of Margaret Hillis as well as the musical world of which she was an important part, but it is much more. Unsung Pioneer is a must-read for its insight on the challenges women (still) face in the musical workplace; on the wider barriers and prejudices found in our modern times and the courage it takes to face adversity; and on the resilience built in the process of getting ever closer to one’s vision of contributing something richly human to a particular corner of the world.<br /><br />Author Dr. Cheryl Frazes Hill conducted, studied, and sang under Ms. Hillis’s mentorship for many years; she had countless opportunities to observe her and learn from her, and she researched virtually every aspect of her life while writing this book.  Dr. Frazes Hill found a way to honor Ms. Hillis’s legacy while helping us to know her better and understand the human side of this musical icon.  Unsung Pioneer brings not only Ms. Hillis to life but also a captivating cast of supporting characters, including familiar musical names who become more real when we read their conversations or learn about their on- or off-the-podium experiences. Dr. Frazes Hill also found ways to weave into the narrative Ms. Hillis’s musical approaches and methods, strongly supported by appendices and references, without interrupting the flow.  Editor Dr. Carroll Gonzo and contributor to the writing process James Yarborough are also to be commended for their roles in this important book.<br /><br />Though I sang under Ms. Hillis for a few Ravinia seasons, I now feel like I know her, and my profession, so much better.  The depth and breadth of Unsung Pioneer make it an immediate classic, a dynamic contribution to the field. Thank you, Dr. Frazes Hill, for telling this story that deserved to be told.', 'parent_asin': '1622775996'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=5178, version=55, score=0.16666667, payload={'preprocessed_data': 'I fell in love with this book! I fell in love with this book! Such a raw, honest look at the feral emotions that taunt us all. Left me feeling empowered and more comfortable in my own skin. And more than a little wild! Lovely, lovely words.', 'parent_asin': 'B0C128NPC9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=6214, version=66, score=0.14285715, payload={'preprocessed_data': 'Great fantasy! Fast paced fantasy novel that keeps you wondering what’s next!', 'parent_asin': 'B0C2S1JJWR'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1180, version=15, score=0.125, payload={'preprocessed_data': "An Honest Portrayal of an Extraordinary Woman I was lucky enough to sing with Ms. Hillis as an undergraduate student, flying standby to and from the Twin Cities to attend her Monday night rehearsals for the upcoming Ravinia season. I ultimately transitioned from singer and voice teacher to choral conductor, so naturally this book was one I had great interest in reading. What I didn't necessarily expect was such a fair, revealing and absorbing read, so meticulously researched and presented.  It's laid out in very digestible chunks so as not to be a chore. This is a book every musician, choral enthusiast, and person in a position of leadership should read. It illuminates one remarkable life, while also shining light on so many universal truths.  Thank you, Cheryl Frazes Hill for this wonderful contribution.  You've done a great service to Ms. Hillis and to our beloved field.", 'parent_asin': '1622775996'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4415, version=48, score=0.11111111, payload={'preprocessed_data': 'A must read! Seeing an author’s heart and soul being poured onto page after page is vulnerable, brave, and wild! Katrina’s words are beautiful thoughts and feelings transformed into poems. This book may have been written for her, but it speaks to all of us!', 'parent_asin': 'B0C128NPC9'}, vector=None, shard_key=None, order_value=None)]

## Define a reviews tool

In [75]:
def retrieve_prefiltered_review_data(query, parent_asins, qdrant_client, k=5):
   
    query_embedding = get_embedding(query)
    results = qdrant_client.query_points(
        collection_name="Amazon-reviews-collection-01",
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion='rrf'),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context = []
    similarity_scores = []
    for result in results.points:
        retrieved_context_ids.append(result.payload["parent_asin"])
        retrieved_context.append(result.payload["preprocessed_data"])
        similarity_scores.append(result.score)

    return {
        "retrieved_context_ids": retrieved_context_ids,
        "retrieved_context": retrieved_context,
        "similarity_scores": similarity_scores
    }

def process_reviews(reviews):
    formatted_reviews = ""
    for id, review in zip(reviews["retrieved_context_ids"], reviews["retrieved_context"]):
        formatted_reviews += f"- ID: {id}, review: {review}\n"
    
    return formatted_reviews


def get_formatted_item_reviews(query: str, items: List[str], top_k: int = 5) -> str:
    """Get the top k reviews matching a query for a list of prefiltered items.

    Args:
        query: The query to get the top k reviews for
        items: The list of item IDs to prefilter for before running the query
        top_k: The number of reviews to retreieve, this should be at least 20 if multiple items are prefiltered
    
    Returns:
        A string of the top k reviews with IDs prepending each review. Each line is a single review for one of the items in the items list.
    """

    qdrant_client = QdrantClient(url="http://localhost:6333")
    reviews = retrieve_prefiltered_review_data(query, items, qdrant_client, top_k)

    return process_reviews(reviews)

In [76]:
result = get_formatted_item_reviews("bad quality", ["1622775996", "B0C128NPC9", "0593547764", "B0C2S1JJWR"])

In [77]:
print(result)

- ID: 0593547764, review: Did not dissapoint I love Greek retellings and this one did not disappoint.  I liked seeing the story of Medusa being told from a different perspective than what we usually get.  I think the author did a great job differentiating each sister's voice, and even if the titles hadn't been the sister's names, you would've been able to distinguish who was narrating.  I did enjoy the overall growth & development of the characters.<br /><br />I did find one of the sisters to be unbearable, and I just disliked her character so much, that it made it hard to read through her chapters, and although I love an advanced vocabulary, I felt distracted by the some of the vocabulary used at times.  Even with not liking the one sister, it was still an entertaining book, and I enjoyed it a whole lot.
- ID: 1622775996, review: The life of a true American classical music pioneer, chronicled in detail. I was Margaret Hillis’ young assistant conductor with the Elgin Symphony for three years in the 1980s, before her schedule got so busy she left her position as music director of the fine professional orchestra she had built in Chicago’s northwest suburbs.<br /><br />As an assignment my very first year I had the privilege (and, I anticipated, the terror) of preparing a local chorus for Miss Hillis to conduct the Beethoven Ninth Symphony with the ESO. Girding myself to be scared and intimidated in my meetings with her beforehand, I found Miss Hillis very much the opposite: invariably gracious, witty, helpful and no-nonsense—she ultimately was pleased with my work.<br /><br />Margaret Hillis and I became friends, (as one was able, considering the difference in our ages), so much so that she accepted my invitation to guest conduct my orchestra in Adrian, Michigan years later, and I visited privately in her dressing room after a rehearsal with the Elgin Symphony when she returned as a guest in 1994. I am told that that evening was the very last time she ever conducted anywhere. More importantly, she recommended me to be the founding conductor of the Chicago Bar Association Symphony, a post I still hold thirty-five years later, an act for which I will always be grateful.<br /><br />Hillis was marvelous at training a chorus. In my experience only her would-be mentor, Robert Shaw, could match her technical ability to get results from choral ensembles, preparing her Chicago Symphony Chorus to be remarkably flexible with CSO music directors as different as Reiner, Martinon, Solti or Barenboim.<br /><br />In performance, especially in front of an orchestra, she was less successful. One evening in fall 1984 I sat out in Hemmens Auditorium in Elgin listening to her lead the ESO in Ravel’s Daphnis & Chloe Suite No. 2. Despite the right notes in the right places, I remember thinking she was only getting about 60% of what I knew from experience the musicians in front of her could give in terms of intensity and emotional commitment. Mine was not a unique general assessment—it was a criticism that dogged Hillis her whole career, as Cheryl Frazes Hill points out numerous times in this exhaustive biography.<br /><br />A lapsed instrumentalist herself, winner of (eventually) nine Grammy Awards, I hardly think Margaret Hillis was intimidated by orchestras. Rather, it may have been exactly her skill at preparing a chorus—her ability to be so self-effacing in front of the music: to teach the notes, rhythms, harmonies, intonation, diction and pronunciation to such a high level of technical proficiency, all without imposing her own personality or injecting her own emotional intensity into the music—which allowed her to remain the favorite of CSO music directors through so many different tenures, temperaments and politics. How much of that self-effacement was innate and how much she forced upon herself to maintain an important position in what was then very much an all-male club Frazes Hill does at times consider; one is left to wonder if Hillis’ greatest skill as a conductor was ultimately her biggest weakness as a performing artist.<br /><br />Nothing I write takes away from what she achieved—indeed, an outdoor stage here at the offices of The American Prize National Nonprofit Competitions in the Performing Arts is named in her memory—nor does it take away from the deep affection I hold for her even now.<br /><br />Margaret Hillis was not the first important female conductor—Antonia Brico and Nadia Boulanger were a generation ahead—but surely she was the first to lead many concerts over many decades with an artistic organization of international stature. She was a true pioneer, a gracious human being and a worthy advocate for music.<br /><br />“Unsung Pioneer” is extremely well researched, highly detailed, balanced, sometimes repetitious and occasionally hyperbolic. Frazes Hill is best at putting in context the career Hillis forged, offering a clear perspective of the times in which she lived…especially as it related to women in professional music in the United States in the decades immediately following the Second World War.<br /><br />It is good to have her story available now, and for all time, through this fine volume. Thanks to Frazes Hill, Margaret Hillis is unsung no longer.
- ID: B0C128NPC9, review: Must read for women! This inspirational book is an absolute must read. I love how Katrina’s vulnerability and raw emotions unfold page after page. It is easy to read in short sessions and gives you a lot to contemplate after. Strong women everywhere will love this compilation.
- ID: 1622775996, review: A Classic This is not just Margaret Hillis’s story—it is our story—conductors, women, musicians of all stripes . . . humans.<br /><br />Unsung Pioneer reads like a novel, captivating in its human drama.  Yes, it is an historical presentation of the life of Margaret Hillis as well as the musical world of which she was an important part, but it is much more. Unsung Pioneer is a must-read for its insight on the challenges women (still) face in the musical workplace; on the wider barriers and prejudices found in our modern times and the courage it takes to face adversity; and on the resilience built in the process of getting ever closer to one’s vision of contributing something richly human to a particular corner of the world.<br /><br />Author Dr. Cheryl Frazes Hill conducted, studied, and sang under Ms. Hillis’s mentorship for many years; she had countless opportunities to observe her and learn from her, and she researched virtually every aspect of her life while writing this book.  Dr. Frazes Hill found a way to honor Ms. Hillis’s legacy while helping us to know her better and understand the human side of this musical icon.  Unsung Pioneer brings not only Ms. Hillis to life but also a captivating cast of supporting characters, including familiar musical names who become more real when we read their conversations or learn about their on- or off-the-podium experiences. Dr. Frazes Hill also found ways to weave into the narrative Ms. Hillis’s musical approaches and methods, strongly supported by appendices and references, without interrupting the flow.  Editor Dr. Carroll Gonzo and contributor to the writing process James Yarborough are also to be commended for their roles in this important book.<br /><br />Though I sang under Ms. Hillis for a few Ravinia seasons, I now feel like I know her, and my profession, so much better.  The depth and breadth of Unsung Pioneer make it an immediate classic, a dynamic contribution to the field. Thank you, Dr. Frazes Hill, for telling this story that deserved to be told.
- ID: B0C128NPC9, review: I fell in love with this book! I fell in love with this book! Such a raw, honest look at the feral emotions that taunt us all. Left me feeling empowered and more comfortable in my own skin. And more than a little wild! Lovely, lovely words.